- .travis.yml
- doc/Jamfile.v2
- doc/tutorial.hpp
- test/Jamfile.v2
This should allow running Hana's tests as part of the whole Boost distribution, which is a requirement for Hana to be shipped with Boost 1.60.
If we provide a Boost.Build-based build system, Boost's regression matrix would be updated automatically by the usual testers, so that would fix #184.
In the current state of affairs, however, the `Jamfile` does not test everything that's being tested by the CMake suite, because setting up everything would be time consuming.
> Add Boost.Build support for the unit tests

- .travis.yml
This avoids building both the push commit and the pull request, which is frankly annoying. Note that this only concerns pull requests coming from branches _inside_ the repository, since push commits from forks are not normally built on Travis.
> [Travis] Do not build branches prefixed with pr/

- appveyor.yml
- cmake/CheckCxxCompilerSupport.cmake
- include/boost/hana/config.hpp
Once merged, this is going to address #207.
Todo:
[Edit: I confirm that `-fms-compatibility-version=18` causes breakage due to missing C++14 facilities, so the smallest admissible value seems to be 19.]
> Add support for Clang-cl with Appveyor

- benchmark/transform/compile.erb.json
- benchmark/transform/compile.hana.types.erb.cpp
- include/boost/hana/detail/any_of.hpp
- include/boost/hana/experimental/types.hpp
- test/detail/any_of.cpp
- test/experimental/types/at.cpp
- test/experimental/types/contains.cpp
- test/experimental/types/drop_front.cpp
- test/experimental/types/equal.cpp
- test/experimental/types/is_empty.cpp
- test/experimental/types/transform.cpp
- test/experimental/types/unpack.cpp
In its current form, Hana cannot easily compete (in terms of compile-time performance) against pure type-level metaprogramming libraries that provide sequences holding types only. This is because `hana::tuple` does so much more than holding types only, and the compiler just has more work to do.
I think the remedy to this is to provide a sequence optimized for holding types only. This way, one would retain the expressive power of Hana, while providing compile-times that are very close to pure type-level sequences. This pull request explores such a sequence.
> Provide a sequence optimized for holding types

- example/filter.cpp
- example/find_if.cpp
- example/group.cpp
- example/iterable/searchable.cpp
- example/misc/printf.cpp
- example/monadic_compose.cpp
- example/remove_if.cpp
- example/tutorial/rationale.container.cpp
- example/tutorial/type.cpp
- example/type/typeid.cpp
- example/unique.cpp
- include/boost/hana/fwd/type.hpp
- include/boost/hana/type.hpp
- test/type/adl.cpp
- test/type/typeid.cpp
Candidate for satisfying #290. I'm still unsure whether using `typeof` would be better, though.
> [type] Add hana::typeid_ and deprecate hana::decltype_

- doc/tutorial.hpp
I found the cheat sheet was missing `index_if`.
I tried having `any_of` use `index_if` but finally realized that `any_of` can take a run-time predicate. :face_with_head_bandage:
> [index_if] Add to Cheatsheet

- .travis.yml
- CMakeLists.txt
- example/chain.cpp
- example/cppcon_2014/functor.cpp
- example/cppcon_2014/matrix.cpp
- example/cppcon_2014/ring.cpp
- example/functional/fix.cpp
- example/integral_constant.cpp
- example/monadic_fold_left.cpp
- example/optional/applicative.complex.cpp
- example/optional/sfinae_friendly_metafunctions.cpp
- include/boost/hana/assert.hpp
- include/boost/hana/cartesian_product.hpp
- include/boost/hana/config.hpp
- include/boost/hana/detail/unpack_flatten.hpp
- include/boost/hana/group.hpp
- include/boost/hana/partition.hpp
That should work out of the box, but (at least) Clang has some bugs that break us when using `-std=c++1z`.
> Make sure we support compiling with C++17

- include/boost/hana/cartesian_product.hpp
- include/boost/hana/view.hpp
- test/view/cartesian_product/at.cpp
- test/view/cartesian_product/is_empty.cpp
- test/view/cartesian_product/length.cpp
- test/view/cartesian_product/modifications.cpp
- test/view/cartesian_product/unpack.cpp
- Adds cartesian_product_view_t and cartesian_product_element_view_t
with specializations for the following:
- at_impl
- is_empty_impl
- length_impl
- unpack_impl
Note: The name `hana::detail::cartesian_product` is being used because I think we can change namespace `detail` here to `view` to expose these functions. This is important since we can't implement Sequence functions as the view "type" is not technically a Sequence.
We could also then change names like `joined` and `flattened` to simply `view::join` and `view::flatten` so the naming is consistent.
> [view] cartesian_product

- include/boost/hana/view.hpp
- All views should use `view_storage` so there can't be
dangling references to view objects when composing views.
- Adds use of `view_storage` in `identity_view` and `single_view`
> [view] Use view_storage in views

- include/boost/hana/fwd/lift.hpp
- include/boost/hana/lift.hpp
Here is my use case to justify this:
```cpp
#include <boost/hana/fwd/lift.hpp>
namespace full_duplex {
struct promise_tag { };
struct promise_fn {
template <typename AsyncFn>
constexpr auto operator()(AsyncFn&&) const;
};
constexpr promise_fn promise{};
constexpr boost::hana::lift_t<promise_tag> promise_lift;
// ^ requires promise_tag to be an Applicative before there is a chance to implement
}
```
BTW
I'm making a clean break and implementing my promise stuff as a proper `hana::Monad`.
Shameless plug: [Generalized Full Duplex Messaging](http://sched.co/EC73)
> [lift] Defer concept check until invocation

- doc/tutorial.hpp
- include/boost/hana/fwd/basic_tuple.hpp
- include/boost/hana/fwd/map.hpp
- include/boost/hana/fwd/optional.hpp
- include/boost/hana/fwd/pair.hpp
- include/boost/hana/fwd/range.hpp
- include/boost/hana/fwd/set.hpp
- include/boost/hana/fwd/string.hpp
- include/boost/hana/fwd/tuple.hpp
- include/boost/hana/map.hpp
- include/boost/hana/set.hpp
- include/boost/hana/tuple.hpp
- test/pair/empty_storage.cpp
- test/tuple/empty_member.cpp
Also, add tests to make sure that an empty pair can be EBO'd. This one is very important because a typical use case is to create a tuple of pairs of empty types (e.g. in `hana::map`), and we expect this to be empty.
Fixes #388
> Make some containers final and add notes about assumptions about representation

- example/tuple/tuple_c.cpp
The documentation states that the result of `tuple_c` is functionally equivalent to the call to `make_tuple` so the example should not require a conversion. Correct me if I am wrong.
I've seen confusion about this before, and here is the question that prompted this:
https://stackoverflow.com/questions/50101953/why-is-the-type-of-boosthanatuple-c-implementation-defined
Thanks :smile:
> [tuple] remove superfluous conversion in example

- include/boost/hana/experimental/printable.hpp
- test/experimental/printable/metafunction.cpp
- Conditionally strips out preceding `struct` keyword since
Microsoft's compiler includes that in the outputs of type_info::name
NOTE: I was not able to test this on Visual C++ as it is closed source and the version is likely not released.
> [experimental] Printable support for Visual C++

- .appveyor.yml
AppVeyor updated its VS2017 image to 15.8.1 on 08/29. So switch to MSVC.
> Switch AppVeyor to use MSVC

- test/type/is_valid.cpp
I am not sure if this is actually supported. My experiment with MSVC is that the compiler ICE  when
instantiating `auto boost::hana::type_detail::is_valid_impl<...>` but let see what the CI says.
> Add a is_valid test for non static member functions

- .travis.yml
- RELEASE_NOTES.md
- benchmark/make/compile.erb.json
- cmake/CheckCxxCompilerSupport.cmake
- doc/js/hana.js
- doc/tutorial.hpp
- include/boost/hana/config.hpp
- include/boost/hana/ext/std/tuple.hpp
- test/CMakeLists.txt
- test/detail/create.cpp
This will make it easier to support new compilers (especially the part where we remove detection of old compilers, which was broken for some new compilers).
> Drop support for old compilers

- include/boost/hana/traits.hpp
- test/type/traits.cpp
Supports #475
- A deprecation warning is thrown (tested on gcc11 with
std=c++17), so just remove the trait for > c++14.
> remove std::is_literal_type that was deprecated

- test/issues/github_460.cpp
identified by clang14 in C++20 mode:
```
test/issues/github_460.cpp:25:33: error: ISO C++20 considers use of overloaded operator '==' (with operand types 'SomeStruct' and 'SomeStruct') to be ambiguous despite there being a unique best viable function [-Werror,-Wambiguous-reversed-operator]
static_assert(SomeStruct{5} == SomeStruct{5}, "");
~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~
test/issues/github_460.cpp:15:20: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
constexpr bool operator==(SomeStruct const& other) {
^
1 error generated.
```
> Add missing const on operator==

- include/boost/hana/core/make.hpp
- include/boost/hana/detail/fast_and.hpp
to avoid warnings in clang 14:
```
In file included from test/headers/boost/hana/any.cpp:1:
In file included from include/boost/hana/any.hpp:15:
In file included from include/boost/hana/any_of.hpp:16:
In file included from include/boost/hana/at.hpp:16:
In file included from include/boost/hana/concept/iterable.hpp:20:
In file included from include/boost/hana/drop_front.hpp:20:
In file included from include/boost/hana/integral_constant.hpp:13:
In file included from include/boost/hana/bool.hpp:17:
In file included from include/boost/hana/core/to.hpp:21:
include/boost/hana/core/make.hpp:35:28: error: left operand of comma operator has no effect [-Werror,-Wunused-value]
static_assert((sizeof...(X), false),
^~~~~~~~~~~~
```
> Cast to void on discarded LHS of comma operator

- include/boost/hana/bool.hpp
- test/integral_constant/udl.cpp
For integral types, you can use a capital `'X'` as part of a hex-prefix, like `0Xdeadbeef`.  This adds support for that to `ic_detail::parse()`.
> Add support for "0X" hex prefix.
